name: Build on Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
      - uses: actions/checkout@v3
      - name: say hi to julien
        run: echo "hello julien"
